#!/usr/bin/env bash
# Transfer file with scp
if [ "$#" -lt 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi
FILE_PATH=$1
IP=$2
UNAME=$3
KEY=$4

scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$UNAME@$IP:~/"
