#!/usr/bin/env bash
#Install nginx

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "server {
    listen 80;
    server_name _;

    location / {
        return 200 'Hello World!\n';
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart

