#!/usr/bin/env bash
#Set redirect_me to google permanently
# Specify the Nginx configuration file
nginx_conf="/etc/nginx/sites-available/default"

#Install nginx

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start

printf "server {
    listen 80;
    server_name _;

    location / {
        return 200 'Hello World!\\n';
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Define the location block to be added
new_location="    location /redirect_me {
        return 301 http://www.google.com;
    }"

# Check if the location block already exists
if grep -q "location /redirect_me {" "$nginx_conf"; then
    echo "Location block already exists. Exiting."
    exit 1
fi

# Use awk to insert the new location block after the 'server {' block
awk -v new_location="$new_location" '/server {/ {print; print new_location; next}1' "$nginx_conf" > "$nginx_conf.tmp" && mv "$nginx_conf.tmp" "$nginx_conf"

# Restart Nginx
sudo service nginx restart 
