#!/usr/bin/env bash
#Script hating on signals
DIR="/var/run/myscript.pid"
pgrep -f "100-process_and_pid_file" > "$DIR"

function cleanup
{
    rm $DIR
    exit
}

trap "echo I hate the kill command && cleanup" SIGTERM
trap "cleanup" SIGQUIT
trap "echo Y U no love me?! && exit" SIGINT

while true;
do
    echo "To infinity and beyond"
    sleep 2
done
