#!/usr/bin/env bash
# fizz-buzz in bash

for i in {1..100}
do
    if ((i % 15 == 0))
    then
	echo "FizzBuzz"
	continue
    fi
    if ((i % 5 == 0))
    then
	echo "Buzz"
	continue
    fi
    if ((i % 3 == 0))
    then
	echo "Fizz"
	continue
    fi
    echo $i
done
