#!/usr/bin/env bash
# Bash script to loop from 1 to 20 and display different messages based on the loop iteration.
# On the 4th iteration, the script displays "4" and "bad luck from China".
# On the 9th iteration, it displays "9" and "bad luck from Japan".
# On the 17th iteration, it displays "17" and "bad luck from Italy".
# For all other iterations, it displays the current loop number.

x=1
while [ $x -lt 21 ];
do
	echo $x
	case $x in
		4)
			echo bad luck from China
			;;
		9)
			echo bad luck from Japan
			;;
		17)
			echo bad luck from Italy
			;;
	esac
	((x++))
done

