#!/usr/bin/env bash
# Print numbers from 1 - 10

i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
	4)
	    echo "bad luck in China"
	    ;;
	9)
	    echo "bad luck in Japan"
	    ;;
	17)
	    echo "bad luck in Italy"
	    ;;
    esac
    ((i++))
done
