#!/usr/bin/env bash
# Change IP for these hosts
# 	 localhost > 127.0.0.2
#	 facebook.com > 8.8.8.8

cp /etc/hosts ~/hosts.bak
echo "127.0.0.1	localhost" > ~/hosts.bak
echo "8.8.8.8	facebook.com" >> ~/hosts.bak

cat ~/hosts.bak > /etc/hosts
